const slugByName = {
  "honey chilli potato": "honey-chilli-potato",
  "veg chowmein": "veg-chowmein",
  "chicken chowmein": "chicken-chowmein",
  "chilli chicken": "chilli-chicken",
  "honey chilli chicken": "honey-chilli-chicken",
  "schezwan chicken": "schezwan-chicken",
  "chilli paneer": "chilli-paneer",
  "tandoori chicken": "tandoori-chicken",
  "plain salad": "indian-salad",
  "green salad": "green-salad",
  "finger salad": "finger-salad",
  "white sauce pasta": "white-sauce-pasta",
  "pink sauce pasta": "pink-sauce-pasta",
  "chicken momos steamed": "steamed-chicken-momos",
  "chicken momos fried": "fried-chicken-momos",
  "chicken momos kfc": "crispy-fried-chicken-momos",
  "malai momos": "malai-momos",
  "tandoori momos": "tandoori-momos",
  "chicken wrap": "chicken-roll",
  "plain naan": "plain-naan",
  "butter naan": "butter-naan",
  "rumali roti": "rumali-roti",
  "tawa roti": "tawa-roti",
  "chicken nuggets": "chicken-nuggets",
  "chicken fingers": "chicken-fingers",
  "crispy paneer": "crispy-paneer",
  "crispy corn": "crispy-corn",
  "virgin mojito": "virgin-mojito",
  "blue curacao": "blue-curacao-mocktail",
  "fresh lime soda": "fresh-lime-soda",
  "deep sea blue": "blue-mocktail",
  "green apple": "green-apple-mocktail",
  "chicken biryani": "chicken-biryani",
  "veg fried rice": "vegetable-fried-rice",
  "schezwan veg fried rice": "schezwan-veg-fried-rice",
  "chicken fried rice": "chicken-fried-rice",
  "schezwan chicken fried rice": "schezwan-chicken-fried-rice",
  "chicken pulav": "chicken-pulao",
  "veg pulav": "vegetable-pulao",
  "plain rice": "plain-rice",
  "zeera rice": "jeera-rice",
  "roasted chicken pizza": "roasted-chicken-pizza",
  "chicken blast pizza": "chicken-blast-pizza",
  "bbq chicken pizza": "bbq-chicken-pizza",
  "mexican bite pizza": "mexican-chicken-pizza",
  "peri peri chicken pizza": "peri-peri-chicken-pizza",
  "butter chicken pizza": "butter-chicken-pizza",
  "golden delight pizza": "golden-delight-pizza",
  "khyenn chyenn special pizza": "special-chicken-pizza",
  "chicken tikka pizza": "chicken-tikka-pizza",
  "tomato paneer pizza": "tomato-paneer-pizza",
  "paneer butter masala pizza": "paneer-butter-masala-pizza",
  "kadhai paneer pizza": "kadhai-paneer-pizza",
  "mattar paneer pizza": "mattar-paneer-pizza",
  "paneer curry pizza": "paneer-curry-pizza",
  "mattar mushroom pizza": "mattar-mushroom-pizza",
  "classic cheese pizza": "cheese-pizza",
  "kids favourite pizza": "cheese-corn-pizza",
  "margarita pizza": "margherita-pizza",
  "schezwan veggie pizza": "schezwan-veg-pizza",
  "khyenn chyenn special veg pizza": "special-veg-pizza",
  "owner special pizza": "special-veg-pizza",
  "spicy paneer pizza": "spicy-paneer-pizza",
  "margarita deluxe pizza": "deluxe-margherita-pizza",
  "pizza toppings": "pizza-toppings",
  "extra cheese": "pizza-toppings",
  "cheese burst": "cheese-burst-pizza",
  "chicken kanti": "chicken-kanti",
  "butter chicken boneless": "butter-chicken",
  "butter chicken with bone": "butter-chicken",
  "chicken curry": "chicken-curry",
  "masala chicken": "masala-chicken",
  "kadhai chicken": "chicken-karahi",
  "wazwan chicken": "wazwan-chicken",
  "onion gravy": "onion-gravy",
  "hot sauce": "hot-sauce",
  "mayonnaise": "mayonnaise",
  "raita": "raita",
  "mint sauce": "mint-chutney",
  "ketchup dip": "ketchup",
  "coffee": "coffee",
  "cappuccino": "cappuccino",
  "lemon tea": "lemon-tea",
  "masala tea": "cutting-chai",
  "kashmiri kehwa": "kashmiri-kahwa",
  "green tea": "green-tea",
  "black coffee": "black-coffee",
};

const SIZE_TOKEN_RE = /\s*\((half|full|regular|large|r|m|l|xl)\)\s*/gi;

function normalizeName(name) {
  return String(name || "")
    .toLowerCase()
    .replace(SIZE_TOKEN_RE, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function imagePathForName(name) {
  const slug = slugByName[normalizeName(name)];
  return slug ? `/images/menu/${slug}.webp` : "";
}

module.exports = { imagePathForName, normalizeName, slugByName };